### ISSUE TITLE
Improve page title with relevant informations

### ISSUE THREAD

**Issue by LeBenLeBen** [team-rawbot/rank-me#103]
At the moment the page title is always "Rank-Me", it should instead represent the content of the page.

**Comment by sephii** [comment]
Could we try to list the page titles we could put on the different URLs?

**Comment by LeBenLeBen** [comment]
I’d suggest having incremental values such as a breadcrumb, with the most specific first.

- Default: Rank-me • Create competitions and track your scores
- Dashboard: Dashboard • Rank-me
- Competition: {competition_name} • Rank-me
- Competition player profile: {full_name} • {competition_name} • Rank-me
- New result: Add result • {competition_name} • Rank-me
- Player profile: {full_name} • Rank-me

All basic pages would just be like: {page_title} • Rank-me (for example "Account settings")
