### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by LeBenLeBen** [team-rawbot/rank-me#104]
Force HTTPS on the whole website.

**Comment by OdyX** [comment]
![image](https://cloud.githubusercontent.com/assets/417403/14647949/391bb0e8-0660-11e6-9ebc-0c70d70c683d.png)

https://www.ssllabs.com/ssltest/analyze.html?d=rank-me.io

#YOLO

**Comment by LeBenLeBen** [comment]
😎
