### ISSUE TITLE
Saving options

### ISSUE THREAD

**Issue by dalanz** [team-rawbot/rank-me#77]
It would be nice to stay on the "Add a Result" page after entering a result. So you won't be redirected to home always and you have to click everything again. This would make the process of adding multiple results much faster and easier. 

Idea: Add a "Add another result" button and rename the default to "Save and return". As a plus, the chosen names would stay selected.

**Comment by LeBenLeBen** [comment]
Yup, we really have to rethink this page as it’s pretty painful to use at the moment. I’ll keep only #58 open if you don’t mind.
