### ISSUE TITLE
Timeline: link on players are wrong

### ISSUE THREAD

**Issue by LeBenLeBen** [team-rawbot/rank-me#97]
On the timeline, all links on players name are wrong and point to another player profile.

**Comment by sephii** [comment]
That's because of the migration process that didn't migrate the team ids in the event details to user ids. New events should have correct links, feel free to reopen if that's not the case.

**Comment by LeBenLeBen** [comment]
Fair enough.

However it links to the player "global" profile. In terms of matches played, it would make more sense to link the profile of the player in the given competition, no?

**Comment by sephii** [comment]
True dat.
