### ISSUE TITLE
Profile header layout is broken

### ISSUE THREAD

**Issue by LeBenLeBen** [team-rawbot/rank-me#98]

**Comment by sephii** [comment]
What's broken?

**Comment by LeBenLeBen** [comment]
Layout 😜

Le Tuesday, April 5, 2016, Sylvain Fankhauser <notifications@github.com> a
écrit :

> What's broken?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/team-rawbot/rank-me/issues/98#issuecomment-205965520>
>


-- 
Liip SA // Rue Etraz 4 // CH-1003 Lausanne
Tel +41 21 533 13 00 // www.liip.ch

**Comment by sephii** [comment]
Screenshot? I can't see anything broken.

**Comment by LeBenLeBen** [comment]
![capture d ecran 2016-04-06 a 08 35 16](https://cloud.githubusercontent.com/assets/793344/14307872/853a1ca0-fbd2-11e5-9352-e87d3640c7a6.png)
